### ISSUE TITLE
Add to `package-sets`?

### ISSUE THREAD

**Issue by paluh** [justinwoo/purescript-record-extra#12]
Is there any reason why this library is not listed in "official" `packages.json` under [purescript/package-sets](https://github.com/purescript/package-sets/)? Should I provide a PR to package-sets which adds this library?

**Comment by justinwoo** [comment]
I just don't know if it's that useful or organized. You might just add it to your own package set for now

**Comment by paluh** [comment]
I want to use this package in a library which I finally want to add to official package-sets too ;-)

Till then I'm going to use it as you suggested and eventually reopen this issue.
