### ISSUE TITLE
RProxy version of keys?

### ISSUE THREAD

**Issue by AlexMouton** [justinwoo/purescript-record-extra#2]
Hey Justin!
Just thinking that an instance of the record isn't always needed for this.
Not confident to recommend replacing Record row in keys with RProxy row, but maybe a second version?

Thanks
A

**Comment by justinwoo** [comment]
Right, the record ends up being a glorified proxy for just about anything will work. I think maybe this kind of definition would work:

```hs
keys :: forall g row rl
   . RowToList row rl
  => Keys rl
  => g row -- so 'g' is just about anything that contains row as a parameter
  -> List String
keys _ = keysImpl (RLProxy :: RLProxy rl)
```

**Comment by justinwoo** [comment]
I pushed it up here: https://github.com/justinwoo/purescript-map-record/commit/d7a5dc7799d91e4aa67a41f2f0a54ff99d502d88
