### ISSUE TITLE
purescript-0.15 support

### ISSUE THREAD

**Issue by goertzenator** [justinwoo/purescript-record-extra#31]
This package appears to have fallen out of package-sets for purescript-0.15.  Can it be updated?

**Comment by justinwoo** [comment]
would you like to help? here's a starter kit for you to contribute the update: https://github.com/justinwoo/purescript-record-extra/tree/0.15.0-starter-kit

**Comment by goertzenator** [comment]
I can pick at it, but it will be at least a few weeks before I can get to it.  Anyway, thanks for the starter kit; that will help a lot!

**Comment by jonathanlking** [comment]
I just updated the FFI file to use ES modules on the `0.15.0-starter-kit` branch and the tests are now passing.
I had a skim of the 0.15.0 [changelog](https://github.com/purescript/purescript/releases/tag/v0.15.0) and the switch from Common JS to ES modules looked like the only breaking change.
It definitely felt too easy, but maybe this was the only change required? 😅

**Comment by JordanMartinez** [comment]
@jonathanlking Did you look through the migration guide? https://github.com/purescript/documentation/blob/master/migration-guides/0.15-Migration-Guide.md

**Comment by jonathanlking** [comment]
@JordanMartinez Thanks for sharing the guide, I didn't, but now have! ✨ 
Apart from ES modules, I _think_ the only other applicable section is on migrating to `Data.Reflectable`, which isn't a requirement until `0.16.0`.
As [`get`](https://github.com/purescript/purescript-record/blob/master/src/Record.purs#L36) from `purescript-record` still uses an `IsSymbol` constraint (rather than `Reflectable`), I don't think we can drop `IsSymbol` from this library yet anyway?

**Comment by JordanMartinez** [comment]
Yeah, continue using `IsSymbol` for now. Switching to `Data.Reflectable` will happen in `0.16.0`

**Comment by goertzenator** [comment]
Just a note: `purescript-dissect` appears to overlap significantly with this package and is in 0.15 package sets.  I've flipped to that package for my app.  Sorry.

**Comment by CGenie** [comment]
Hello,
Anyone has code that could be merged? If not, please point me to your branch if it has some more work over Justin's https://github.com/justinwoo/purescript-record-extra/tree/0.15.0-starter-kit ? I can pick it up.

**Comment by i-am-the-slime** [comment]
I'd also very much like a release of `0.15.0-starter-kit` @jonathanlking

**Comment by justinwoo** [comment]
https://github.com/justinwoo/purescript-record-extra/releases/tag/v5.0.0
