### ISSUE TITLE
Record wrapper with `Monoid` and `Eq` instances

### ISSUE THREAD

**Issue by paluh** [justinwoo/purescript-record-extra#6]
@justinwoo Are you interested in this kind of wrapper around record: https://gist.github.com/paluh/fd49a4e0f1065967783f23911a0b4466#file-extra-purs-L102 ?

**Comment by AdamSaleh** [comment]
@paluh, I think the code you have here is almost the same thing I have in the open PR #5, AFAIK it is 80% your code anyway :) My version is missing the newtypws though, so I am wondering, how would they help? I kinda assumed I would have to define new Newtype for every new row, to avoid overlapping instances. Did I miss something?

**Comment by paluh** [comment]
@AdamSaleh You are right - implementation of `appendRecord` or `eqRecord` is not really a subject of this proposition.
I'm asking whether we want to provide a `newtype Record'` wrapper so I can wrap regular record in it (`Record' {...}`) and pass into a function which has for example `Semigroup` constraint on given input type.

**Comment by justinwoo** [comment]
Closing to clean up my feed
