### ISSUE TITLE
ordRecord

### ISSUE THREAD

**Issue by matthewleon** [justinwoo/purescript-record-extra#7]
Is there any interest in an `ordRecord` in the spirit of `eqRecord`?

**Comment by justinwoo** [comment]
If it can be done, why not I guess :smile: I'd really love for most of these things to be in 0.12's prelude of course

**Comment by matthewleon** [comment]
> I'd really love for most of these things to be in 0.12's prelude of course

Agreed. But who knows when that happens?

**Comment by matthewleon** [comment]
merged: https://github.com/justinwoo/purescript-record-extra/commit/aa251ec2aa6b9551eceef684a007097d0ece5d2d
